"""empty message

Revision ID: 5dfa8d75c9aa
Revises: da85f23badbe
Create Date: 2020-12-25 14:31:44.820883

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5dfa8d75c9aa'
down_revision = 'da85f23badbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cms_user', sa.Column('_password', sa.String(length=50), nullable=False))
    op.drop_column('cms_user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cms_user', sa.Column('password', mysql.VARCHAR(collation='utf8mb4_bin', length=50), nullable=False))
    op.drop_column('cms_user', '_password')
    # ### end Alembic commands ###
